name: PullRequest & Push master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Setup node env 🏗
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml
            playground/pnpm-lock.yaml

      - name: Enable Corepack
        run: corepack enable

      - name: Install Module deps 🛠️
        run: pnpm install --frozen-lockfile
        working-directory: ./

      - name: Install Playground deps 🛠️
        run: pnpm install --frozen-lockfile
        working-directory: ./playground

      - name: Run Prepare 🛠️
        run: pnpm dev:prepare

      - name: Lint code 👀️
        run: pnpm lint
        continue-on-error: true

      - name: Prepack code 🧪
        run: pnpm prepack
