name: PullRequest & Push master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: merkaly-io/actions/setup@master

      - run: pnpm lint
        continue-on-error: true

      - run: pnpm prepack
