name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: merkaly-io/actions/setup@master

      - run: |
          git fetch origin master --force --tags
          git merge-base --is-ancestor "$GITHUB_SHA" origin/master
        shell: bash

      - run: |
          TAG_VERSION="${GITHUB_REF_NAME#v}"
          PACKAGE_VERSION="$(node -p "JSON.parse(require('fs').readFileSync('package.json', 'utf8')).version")"
          test "$TAG_VERSION" = "$PACKAGE_VERSION"
        shell: bash

      - run: pnpm lint
        continue-on-error: true
        shell: bash

      - run: pnpm build
        shell: bash

      - uses: merkaly-io/actions/publish@master

  release:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: merkaly-io/actions/release@master
